apiVersion: v1
kind: Secret
metadata:
  name: core-event-secret
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: imstargg
type: Opaque
data:
  PLAYER_RENEWAL_QUEUE_NAME: {{ .Values.queue.playerRenewal.name | b64enc | quote }}
