apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db-core.fullname" . }}-secret
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: imstargg
type: Opaque
data:
  url: {{ .Values.database.url | b64enc | quote }}
  username: {{ .Values.database.username | b64enc | quote }}
  password: {{ .Values.database.password | b64enc | quote }}