apiVersion: v1
kind: Secret
metadata:
  name: db-core-secret
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: imstargg
type: Opaque
data:
  DATABASE_URL: {{ .Values.database.url | b64enc | quote }}
  DATABASE_USERNAME: {{ .Values.database.username | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc | quote }}