apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aws.secretName" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: imstargg
type: Opaque
data:
  AWS_ACCESS_KEY: {{ .Values.aws.credentials.accessKey | b64enc | quote }}
  AWS_SECRET_KEY: {{ .Values.aws.credentials.secretKey | b64enc | quote }}
  {{- if .Values.aws.sqs.enabled }}
  PLAYER_RENEWAL_QUEUE_NAME: {{ .Values.aws.sqs.queue.playerRenewal.name | b64enc | quote }}
  {{- end }}