apiVersion: v1
kind: Secret
metadata:
  name: alert-manager-secret
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: imstargg
type: Opaque
data:
  DISCORD_WEBHOOK_URL: {{ .Values.discordWebHookUrl | b64enc | quote }}
