spring:
  config:
    import:
      - db-core.yml
      - core-event.yml
      - brawlstars-client.yml
      - aws-sqs.yml
      - logging.yml
      - monitoring.yml

  cloud:
    aws:
      sqs:
        listener:
          max-concurrent-messages: 10
          max-messages-per-poll: 10
          poll-timeout: 10s

  task:
    execution:
      thread-name-prefix: "worker-task-"
      pool:
        core-size: 10
        max-size: 10
        queue-capacity: 10000
      shutdown:
        await-termination: true
        await-termination-period: 10000

---
spring:
  config.activate.on-profile: local


---
spring:
  config.activate.on-profile: local-dev

---
spring:
  config.activate.on-profile: dev

---
spring:
  config.activate.on-profile: live

