spring:
  application.name: worker

  profiles.active: local

  config:
    import:
      - core-db.yml
      - core-event.yml
      - brawlstars-client.yml
      - logging.yml
      - monitoring.yml

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 30
          batch_versioned_data: false
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 500

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

---
spring:
  config:
    activate:
      on-profile: local

#logging.level:
#  org.hibernate:
#    SQL: debug
#    orm.jdbc.bind: trace

---
spring:
  config:
    activate:
      on-profile: local-dev

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: live

