export const BattleEventModeValue = {

  BOUNTY: 'BOUNTY',
  BRAWL_BALL: 'BRAWL_BALL',
  KNOCKOUT: 'KNOCKOUT',
  WIPEOUT: 'WIPEOUT',
  GEM_GRAB: 'GEM_GRAB',
  HOT_ZONE: 'HOT_ZONE',
  HEIST: 'HEIST',
  DUELS: 'DUELS',
  BASKET_BRAWL: 'BASKET_BRAWL',
  VOLLEY_BRAWL: 'VOLLEY_BRAWL',
  SOLO_SHOWDOWN: 'SOLO_SHOWDOWN',
  DUO_SHOWDOWN: 'DUO_SHOWDOWN',
  TRIO_SHOWDOWN: 'TRIO_SHOWDOWN',
  KNOCKOUT_5V5: 'KNOCKOUT_5V5',
  WIPEOUT_5V5: 'WIPEOUT_5V5',
  BRAWL_BALL_5V5: 'BRAWL_BALL_5V5',
  GEM_GRAB_5V5: 'GEM_GRAB_5V5',
  SIEGE: 'SIEGE',
  PAYLOAD: 'PAYLOAD',
  PAINT_BRAWL: 'PAINT_BRAWL',
  TROPHY_THIEVES: 'TROPHY_THIEVES',
  BIG_GAME: 'BIG_GAME',
  BOSS_FIGHT: 'BOSS_FIGHT',
  BOT_DROP: 'BOT_DROP',
  HUNTERS: 'HUNTERS',
  JELLYFISHING: 'JELLYFISHING',
  PRESENT_PLUNDER: 'PRESENT_PLUNDER',
  ROBO_RUMBLE: 'ROBO_RUMBLE',
  TAKEDOWN: 'TAKEDOWN',
  TROPHY_ESCAPE: 'TROPHY_ESCAPE',
  LONE_STAR: 'LONE_STAR',
  SUPER_CITY_RAMPAGE: 'SUPER_CITY_RAMPAGE',
  HOLD_THE_TROPHY: 'HOLD_THE_TROPHY',
  LAST_STAND: 'LAST_STAND',
  SNOWTEL_THIEVES: 'SNOWTEL_THIEVES',
  PUMPKIN_PLUNDER: 'PUMPKIN_PLUNDER',
  GODZILLA_CITY_SMASH: 'GODZILLA_CITY_SMASH',
  ZOMBIE_PLUNDER: 'ZOMBIE_PLUNDER',

  UNKNOWN: 'UNKNOWN',
  NOT_FOUND: 'NOT_FOUND',
} as const;

export type BattleEventMode = typeof BattleEventModeValue[keyof typeof BattleEventModeValue];

export const BattleEventModeValues = Object.keys(BattleEventModeValue) as BattleEventMode[];

const resultBattleEventModes: BattleEventMode[] = [
  BattleEventModeValue.SOLO_SHOWDOWN,
  BattleEventModeValue.DUO_SHOWDOWN,
  BattleEventModeValue.TRIO_SHOWDOWN,
  BattleEventModeValue.HUNTERS,
  BattleEventModeValue.TROPHY_ESCAPE,
  BattleEventModeValue.TAKEDOWN,
];

export const isResultBattleEventMode = (battleEventMode: BattleEventMode): boolean => {
  return resultBattleEventModes.includes(battleEventMode);
};