apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brawlStarsClient.secretName" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: imstargg
type: Opaque
data:
  BRAWL_STARS_API_KEY: {{ include "brawlStarsClient.keys" . | b64enc | quote }}
