spring:
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
---
spring:
  config.activate.on-profile: test
  cloud:
    aws:
      credentials:
        access-key: test-aws-access-key
        secret-key: test-aws-secret-key
