spring:
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 5
      connection-timeout: 1100
      validation-timeout: 1000
      keepalive-time: 30000
      max-lifetime: 1800000
      data-source-properties:
        socketTimeout: 3000

---
spring:
  config:
    activate:
      on-profile: live

  datasource:
    hikari:
      minimum-idle: 20
      maximum-pool-size: 30