spring:
  application:
    name: imstargg-admin

  config.import:
    - db-core.yml
    - aws.yml

  profiles:
    active: local

  web.resources.add-mappings: false
  mvc.problemdetails.enabled: true
---
spring:
  config.activate.on-profile: local

logging.level:
    org.apache.coyote.http11: trace

---
spring:
  config.activate.on-profile: live
