spring:
  application:
    name: imstargg-admin

  config.import:
    - core-db.yml

  profiles:
    active: local

---
spring:
  config.activate.on-profile: local

logging.level:
    org.apache.coyote.http11: trace

---
spring:
  config.activate.on-profile: live
