spring:
  config.import:
    - client.yml

  cloud.openfeign:
    client:
      config:
        brawlstars-news:
          connect-timeout: 2100
          read-timeout: 5000
          logger-level: BASIC


app.client.brawlstars-news:
  url: https://supercell.com

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile:
  - local-dev
  - dev

---
spring.config.activate.on-profile:
  - live

spring.cloud.openfeign.client.config.brawlstars.loggerLevel: NONE
