package com.imstargg.core.enums;

public enum BattleEventMap {

    NOT_FOUND(null),

    ABYSSAL_ASSAULT("Abyssal Assault"),
    ACID_LAKES("Acid Lakes"),
    ACUTE_ANGLE("Acute Angle"),
    AFTERPIECE_ARENA("Afterpiece Arena"),
    AIR_WAYBILL("Air Waybill"),
    ARCTIC_EXTRACTION("Arctic Extraction"),
    BACK_POCKET("Back Pocket"),
    BACKHAUL("Backhaul"),
    BACKYARD_BOWL("Backyard Bowl"),
    BALL_HOG("Ball Hog"),
    BASKET_FORT("Basket Fort"),
    BEACH_BALL("Beach Ball"),
    BELLES_ROCK("Belle's Rock"),
    BETWEEN_THE_RIVERS("Between the Rivers"),
    BLOCK_AND_COUNTER("Block and Counter"),
    BLOCK_PARTY("Block Party"),
    BOSS_FIGHT("Boss Fight"),
    BOT_DROP("Bot Drop"),
    BOUNCING_DINER("Bouncing Diner"),
    BOXED_IN("Boxed In"),
    BREAKS("Breaks"),
    BRIDGE_TOO_FAR("Bridge Too Far"),
    BROILER_ROOM("Broiler Room"),
    BURNING_FLARES("Burning Flares"),
    CAMPING_GROUNDS("Camping Grounds"),
    CANAL_GRANDE("Canal Grande"),
    CANYON_RIVERS("Canyon Rivers"),
    CAVERN_CHURN("Cavern Churn"),
    CENTER_CONTROL("Center Control"),
    CENTER_STAGE("Center Stage"),
    CHECKERED("Checkered"),
    CHEEKY_CHOKEPOINT("Cheeky Chokepoint"),
    CHILL_SPACE("Chill Space"),
    CLOSE_CALL("Close Call"),
    CLOSE_QUARTERS("Close Quarters"),
    COARSE_COURSE("Coarse Course"),
    COCONUT_COVE("Coconut Cove"),
    COLD_POND_QUARRY("Cold Pond Quarry"),
    CONTROLLER_CHAOS("Controller Chaos"),
    COOKED_CRABS_COVE("Cooked Crabs Cove"),
    COOL_SHAPES("Cool Shapes"),
    COVER_CROWD("Cover Crowd"),
    CRISPY_CRYPT("Crispy Crypt"),
    CROSSROADS("Crossroads"),
    CRYSTAL_ARCADE("Crystal Arcade"),
    CUBIC_CAPACITY("Cubic Capacity"),
    DANGER_ZONE("Danger Zone"),
    DARK_PASSAGE("Dark Passage"),
    DAYLIGHT_ROBBERY("Daylight Robbery"),
    DEATHCAP_TRAP("Deathcap Trap"),
    DEEP_DINER("Deep Diner"),
    DEEP_END("Deep End"),
    DIAGONAL_ALLEY("Diagonal Alley"),
    DIAMOND_DOME("Diamond Dome"),
    DIAMOND_DUST("Diamond Dust"),
    DOUBLE_TROUBLE("Double Trouble"),
    DRIED_UP_RIVER("Dried Up River"),
    DRIED_UP_RIVER_2("Dried Up River"),
    DRY_SEASON("Dry Season"),
    DUELING_BEETLES("Dueling Beetles"),
    DUELISTS_DESTINY("Duelist's Destiny"),
    DUNE_DRIFT("Dune Drift"),
    DYE_DIRECT("Dye Direct"),
    ENCIRCLEMENT("Encirclement"),
    ERRATIC_BLOCKS("Erratic Blocks"),
    EXCEL("Excel"),
    EYE_OF_THE_STORM("Eye of the Storm"),
    FEAST_OR_FAMINE("Feast or Famine"),
    FIELD_GOAL("Field Goal"),
    FIRM_GRIP("Firm Grip"),
    FLARING_PHOENIX("Flaring Phoenix"),
    FLOODED_DAM("Flooded Dam"),
    FLOODED_MINE("Flooded Mine"),
    FLOWING_SPRINGS("Flowing Springs"),
    FLYING_FANTASIES("Flying Fantasies"),
    FORSAKEN_FALLS("Forsaken Falls"),
    FOUR_LEVELS("Four Levels"),
    FOURSQUARE_FORTRESS("Foursquare Fortress"),
    FREEZING_RIPPLES("Freezing Ripples"),
    FROSTY_TRACKS("Frosty Tracks"),
    GEM_EXCHANGE("Gem Exchange"),
    GEM_FORT("Gem Fort"),
    GEM_SOURCE("Gem Source"),
    GG_MORTUARY("G.G. Mortuary"),
    GLASS_HALF_FULL("Glass Half Full"),
    GOALKEEPERS_DREAM("Goalkeeper's Dream"),
    GOLDARM_GULCH("Goldarm Gulch"),
    GRASSY_GORGE("Grassy Gorge"),
    GREAT_WAVES("Great Waves"),
    GREASEPAINT_GRASS("Greasepaint Grass"),
    HARD_LIMITS("Hard Limits"),
    HARD_LANE("Hard Lane"),
    HARD_ROCK_MINE("Hard Rock Mine"),
    HEAT_WAVE("Heat Wave"),
    HEALTHY_MIDDLE_GROUND("Healthy Middle Ground"),
    HELLISH_HARVEST("Hellish Harvest"),
    HIDDEN_ENEMY("Hidden Enemy"),
    HIDEOUT("Hideout"),
    HIGHLY_TRAFFICATED("Highly Trafficated"),
    HOT_MAZE("Hot Maze"),
    HOT_POTATO("Hot Potato"),
    HUNGRY_HIPPOS("Hungry Hippos"),
    HUNTERS("Hunters"),
    ICY_ICE_PARK("Icy Ice Park"),
    IMBALANCE("Imbalance"),
    INFINITE_DOOM("Infinite Doom"),
    INFERNAL_INVASION("Infernal Invasion"),
    INTO_INFINITY("Into Infinity"),
    IRON_BARS("Iron Bars"),
    IRON_CENTER("Iron Center"),
    IRON_CORE("Iron Core"),
    IRON_CORRIDOR("Iron Corridor"),
    IRON_COVER("Iron Cover"),
    IRON_STANDOFF("Iron Standoff"),
    ISLAND_HOPPING("Island Hopping"),
    ISLAND_INVASION("Island Invasion"),
    ISOLATION_PLAY("Isolation Play"),
    JUNGLE_BALL("Jungle Ball"),
    KABOOM_CANYON("Kaboom Canyon"),
    LAYER_BAKE("Layer Bake"),
    LAYER_CAKE("Layer Cake"),
    LEAPING_FROGS("Leaping Frogs"),
    LINE_OF_DEFENSE("Line of Defense"),
    LUIS_REVENGE("Luis' Revenge"),
    LUSH_POLES("Lush Poles"),
    MACHINE_ZONE("Machine Zone"),
    MAKE_IT_BOUNCE("Make it Bounce"),
    MANTIS_CLAW("Mantis Claw"),
    MARKSMANS_PARADISE("Marksman's Paradise"),
    MEADOW_OF_THE_CRANE("Meadow of the Crane"),
    METAL_SCRAP("Metal Scrap"),
    MIDDLE_GROUND("Middle Ground"),
    MIDLANDS("Midlands"),
    MINECART_MADNESS("Minecart Madness"),
    MONKEY_MAZE("Monkey Maze"),
    MYSTIC_TOUCH("Mystic Touch"),
    NEW_HORIZONS("New Horizons"),
    NEW_PERSPECTIVE("New Perspective"),
    NIGHT_AT_THE_MUSEUM("Night at the Museum"),
    NINJA_CHECKMATE("Ninja Checkmate"),
    NO_EXCUSES("No Excuses"),
    NO_SURRENDER("No Surrender"),
    NUTS_AND_BOLTS("Nuts & Bolts"),
    ON_THE_TRAIN("On the Train"),
    OPEN_BUSINESS("Open Business"),
    OPEN_SPACE("Open Space"),
    OPEN_ZONE("Open Zone"),
    OPPOSING_FORTS("Opposing Forts"),
    OUT_IN_THE_OPEN("Out in the Open"),
    OUTLAW_CAMP("Outlaw Camp"),
    OUTRAGEOUS_OUTBACK("Outrageous Outback"),
    OVER_THE_TOP("Over the Top"),
    PANCAKE("Pancake"),
    PARALLEL_PLAYS("Parallel Plays"),
    PICK_AND_ROLL("Pick and Roll"),
    PILLARS_OF_DOOM("Pillars of Doom"),
    PINBALL_DREAMS("Pinball Dreams"),
    PINHOLE_PUNT("Pinhole Punt"),
    PIT_STOP("Pit Stop"),
    POCKET_PASS("Pocket Pass"),
    POISON_FIELDS("Poison Fields"),
    POST_HASTE("Post Haste"),
    POWER_ALLEY("Power Alley"),
    POWER_SHOT("Power Shot"),
    PURPLE_PARADISE("Purple Paradise"),
    QUAD_DAMAGE("Quad Damage"),
    QUARTER_POUNDER("Quarter Pounder"),
    RADIANT_RAMPAGE("Radiant Rampage"),
    RAZZLE_DAZZLE("Razzle Dazzle"),
    REFLECTIONS("Reflections"),
    RETINA("Retina"),
    RIGID_RAVINES("Rigid Ravines"),
    RING_OF_FIRE("Ring of Fire"),
    RING_O_BRAWLIN("Ring 'o Brawlin"),
    RIVERSIDE("Riverside"),
    RIVERBED("Riverbed"),
    ROCKWALL_BRAWL("Rockwall Brawl"),
    ROLLING_RUMBLE("Rolling Rumble"),
    RUSH("Rush"),
    RUSTY_REBOUND("Rusty Rebound"),
    SAFE_ZONE("Safe Zone"),
    SAFETY_CENTER("Safety Center"),
    SAPPHIRE_PLAINS("Sapphire Plains"),
    SCORCHED_STONE("Scorched Stone"),
    SHOOTING_STAR("Shooting Star"),
    SHROUDING_SERPENT("Shrouding Serpent"),
    SHIVER_ME_TIMBERS("Shiver me Timbers"),
    SHUFFLE_CITY("Shuffle City"),
    SIEGE("Siege"),
    SIDE_BY_SIDE("Side by Side"),
    SIZZLING_CHAMBERS("Sizzling Chambers"),
    SKULL_CREEK("Skull Creek"),
    SLAM_DUNK("Slam Dunk"),
    SLALOM_SLAM("Slalom Slam"),
    SLAYERS_PARADISE("Slayer's Paradise"),
    SLIPPERY_ROAD("Slippery Road"),
    SNAKE_PRAIRIE("Snake Prairie"),
    SNOWFLAKES("Snowflakes"),
    SNOWMAN_FOREST("Snowman Forest"),
    SOLID_CENTER("Solid Center"),
    SOME_ASSEMBLY_REQUIRED("Some Assembly Required"),
    SPICE_PRODUCTION("Spice Production"),
    SPLIT("Split"),
    SPLIT_SECOND("Split Second"),
    SPRING_TRAP("Spring Trap"),
    SQUARE_OFF("Square Off"),
    STARR_FISH("Starr Fish"),
    STAY_IN_YOUR_LANE("Stay in your Lane"),
    STEPPING_STONES("Stepping Stones"),
    STORMY_PLAINS("Stormy Plains"),
    STRONG_SIDE("Strong Side"),
    SULTANS_OF_SWING("Sultans of Swing"),
    SUNSET_VISTA("Sunset Vista"),
    SUPER_BEACH("Super Beach"),
    SWALLOW_CUT("Swallow Cut"),
    SWIMMING_SKILLS("Swimming Skills"),
    TAKEDOWN("Takedown"),
    TANGLED_SHRUBS("Tangled Shrubs"),
    TEAM_DAY("Team Day"),
    TEMPLE_OF_BOOM("Temple of Boom"),
    TEMPLE_RUINS("Temple Ruins"),
    THE_GALAXY("The Galaxy"),
    THE_GREAT_DIVIDE("The Great Divide"),
    THE_GREAT_OPEN("The Great Open"),
    THOUSAND_JELLIES("Thousand Jellies"),
    TIGER_LEAP("Tiger Leap"),
    TIGER_TRAP("Tiger Trap"),
    TOO_COOL_FOR_SUMMER("Too cool for Summer"),
    TORNADO_RING("Tornado Ring"),
    TOUCH_UP_TAVERN("Touch Up Tavern"),
    TRANSFER_OF_TROUBLES("Transfer of Troubles"),
    TREEFECTA("Treefecta"),
    TRIPLE_DRIBBLE("Triple Dribble"),
    TRIPLE_DOUBLE("Triple-Double"),
    TRIUMVIRATE("Triumvirate"),
    TROPHY_TRESPASS("Trophy Trespass"),
    TURNOVER("Turnover"),
    TWILIGHT_PASSAGE("Twilight Passage"),
    UNDERMINE("Undermine"),
    UNDERWORLD_UPRISING("Underworld Uprising"),
    VICTORY_ROAD("Victory Road"),
    WARPED_BEACH("Warped Beach"),
    WARRIORS_WAY("Warrior's Way"),
    WATERS_OF_DOOM("Waters of Doom"),
    WEAK_FOOT("Weak Foot"),
    WELL_CUT("Well Cut"),
    WINTER_PARTY("Winter Party"),
    ZIP_LINE("Zip Line"),
    ZOOMED_OUT("Zoomed Out"),
    SNEAKY_FIELDS("Sneaky Fields"),
    DOUBLE_SWOOSH("Double Swoosh"),
    SUNNY_SOCCER("Sunny Soccer"),
    FORCE_MAJEURE("Force Majeure"),
    OFF_THE_LINE("Off the Line"),;

    private final String name;

    BattleEventMap(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
