
---
spring:
  config:
    activate:
      on-profile:
      - local
      - local-dev

---
spring:
  config:
    activate:
      on-profile:
      - dev
      - live

app:
  alert:
    type: DISCORD
    discord.webhook-url: ${DISCORD_WEBHOOK_URL}
