spring:
  application.name: batch

  profiles.active: local

  config:
    import:
      - core-db.yml
      - brawlstars-client.yml
      - logging.yml

  batch:
    job:
      enabled: true
      name: ${job.name:healthCheckJob}
    jdbc:
      initialize-schema: never
      isolation-level-for-create: default

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 30
        batch_versioned_data: true
        order_inserts: true
        order_updates: true

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: local-dev

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod

