spring:
  config.import:
    - db-core.yml
    - cache-core.yml
    - core-event.yml
    - aws-sqs.yml

  task:
    execution:
      thread-name-prefix: "core-task-"
      pool:
        core-size: 10
        max-size: 10
        queue-capacity: 10000
      shutdown:
        await-termination: true
        await-termination-period: 10000