apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "batch.fullname" . }}
  labels:
    {{- include "batch.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.job.schedule | quote }}
  concurrencyPolicy: {{ .Values.job.concurrencyPolicy | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "batch.labels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          restartPolicy: OnFailure
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              {{- with .Values.app.job.parameters }}
              args:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: {{ .Values.app.profile | quote }}
                - name: SPRING_BATCH_JOB_NAME
                  value: {{ .Values.app.job.name | quote }}
              envFrom:
                - secretRef:
                    name: {{ .Values.app.secret.db }}
                - secretRef:
                    name: {{ .Values.app.secret.alertManager }}
                - secretRef:
                    name: {{ .Values.app.secret.brawlStarsClient }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              {{- with .Values.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- with .Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
