spring:

  config.import:
    - client.yml

  cloud.openfeign:
    client:
      config:
        brawlstars:
          connect-timeout: 2100
          read-timeout: 5000
          logger-level: BASIC

resilience4j:
  ratelimiter:
    metrics:
      enabled: false
    instances:
      brawlstars-api:
        limit-for-period: 1
        limit-refresh-period: 1s
        timeout-duration: 600s


app.client.brawlstars:
  url: https://api.brawlstars.com
  key: ${BRAWL_STARS_API_KEY}

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile:
  - local-dev
  - dev

---
spring.config.activate.on-profile:
  - live

resilience4j:
  ratelimiter:
    instances:
      brawlstars-api:
        limit-for-period: 100

spring.cloud.openfeign.client.config.brawlstars.loggerLevel: NONE
